import type { Customer } from '../types/customer';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: '1',
    name: 'أحمد عبدالله الراجحي',
    type: 'individual',
    typeLabel: 'عميل أفراد',
    nationalOrCrId: '1029384756',
    totalDebt: 45000,
    totalPaid: 15000,
    status: 'overdue',
    statusLabel: 'متأخر',
    avatarLetter: 'أ',
    avatarBg: 'bg-rose-100 text-rose-600',
    phone: '0501234567',
    email: 'ahmed.rajhi@example.com',
    address: 'الرياض - حي الياسمين',
    registrationDate: '2024-01-15',
    transactions: [
      {
        id: 'tx-101',
        date: '2024-08-10',
        type: 'debt',
        typeLabel: 'فاتورة مبيعات آجل',
        amount: 30000,
        status: 'overdue',
        statusLabel: 'متأخر',
        invoiceNumber: 'INV-2024-001',
        notes: 'دفعة مستحقة منذ 15 يوماً',
      },
      {
        id: 'tx-102',
        date: '2024-07-20',
        type: 'debt',
        typeLabel: 'فاتورة خدمات إضافية',
        amount: 15000,
        status: 'overdue',
        statusLabel: 'متأخر',
        invoiceNumber: 'INV-2024-002',
        notes: 'استحقاق السداد نهاية الشهر الماضي',
      },
      {
        id: 'tx-103',
        date: '2024-06-05',
        type: 'payment',
        typeLabel: 'سداد نقدي / حوالة',
        amount: 15000,
        status: 'completed',
        statusLabel: 'مكتمل',
        invoiceNumber: 'PAY-2024-099',
        notes: 'سداد عن طريق تحويل بنكي',
      },
    ],
  },
  {
    id: '2',
    name: 'شركة التقنية المتقدمة',
    type: 'company',
    typeLabel: 'عميل شركات',
    nationalOrCrId: '7001234567',
    totalDebt: 120500,
    totalPaid: 80000,
    status: 'active_debt',
    statusLabel: 'دين نشط',
    avatarLetter: 'ش',
    avatarBg: 'bg-indigo-100 text-indigo-600',
    phone: '0559876543',
    email: 'finance@advtech.sa',
    address: 'جدة - طريق الملك عبدالعزيز',
    registrationDate: '2023-11-20',
    transactions: [
      {
        id: 'tx-201',
        date: '2024-08-18',
        type: 'debt',
        typeLabel: 'عقد توريد أجهزة',
        amount: 120500,
        status: 'pending',
        statusLabel: 'قيد الاستحقاق',
        invoiceNumber: 'INV-2024-045',
        notes: 'مستحق السداد خلال 30 يوم',
      },
      {
        id: 'tx-202',
        date: '2024-05-12',
        type: 'payment',
        typeLabel: 'سداد دفعة عقد',
        amount: 80000,
        status: 'completed',
        statusLabel: 'مكتمل',
        invoiceNumber: 'PAY-2024-032',
        notes: 'تم سداد الدفعة الأولى',
      },
    ],
  },
  {
    id: '3',
    name: 'سالم محمد الدوسري',
    type: 'individual',
    typeLabel: 'عميل أفراد',
    nationalOrCrId: '1098765432',
    totalDebt: 0,
    totalPaid: 45000,
    status: 'paid',
    statusLabel: 'تم السداد',
    avatarLetter: 'س',
    avatarBg: 'bg-emerald-100 text-emerald-600',
    phone: '0543219876',
    email: 'salem.aldossari@example.com',
    address: 'الدمام - حي الشاطئ',
    registrationDate: '2024-02-10',
    transactions: [
      {
        id: 'tx-301',
        date: '2024-06-15',
        type: 'payment',
        typeLabel: 'سداد كامل الرصيد',
        amount: 45000,
        status: 'completed',
        statusLabel: 'مكتمل',
        invoiceNumber: 'PAY-2024-077',
        notes: 'تم تصفية الحساب بالكامل',
      },
    ],
  },
  {
    id: '4',
    name: 'مؤسسة البناء الحديث',
    type: 'company',
    typeLabel: 'عميل شركات',
    nationalOrCrId: '7009876543',
    totalDebt: 15750,
    totalPaid: 60000,
    status: 'active_debt',
    statusLabel: 'دين نشط',
    avatarLetter: 'م',
    avatarBg: 'bg-blue-100 text-blue-600',
    phone: '0567891234',
    email: 'contact@modernbuild.sa',
    address: 'الرياض - حي الملز',
    registrationDate: '2023-09-05',
    transactions: [
      {
        id: 'tx-401',
        date: '2024-08-01',
        type: 'debt',
        typeLabel: 'مواد بناء وتجهيزات',
        amount: 15750,
        status: 'pending',
        statusLabel: 'قيد الاستحقاق',
        invoiceNumber: 'INV-2024-112',
        notes: 'الدفعة الأخيرة للعقد',
      },
    ],
  },
];

export function getCustomerById(id: string): Customer | undefined {
  return MOCK_CUSTOMERS.find((c) => c.id === id);
}
