import { httpClient, ApiError } from '../api/httpClient';
import type {
  CreateInvoiceCommand,
  CreateInvoiceResponseDto,
  ShareInvoiceRequest,
  ShareInvoiceResponseDto,
} from '../types/invoice';

/**
 * POST /api/Invoice
 * Creates an electronic invoice tied to a debt or payment.
 */
export async function createInvoice(
  command: CreateInvoiceCommand
): Promise<CreateInvoiceResponseDto> {
  return httpClient.post<CreateInvoiceResponseDto>('/Invoice', command);
}

/**
 * GET /api/Invoice/{id}/pdf
 * Fetches the official PDF binary stream generated by the server.
 * Defaults to 15 if no ID provided.
 */
export async function getInvoicePdfBlob(invoiceId: number | string = 15): Promise<Blob> {
  const cleanId = String(invoiceId).replace(/[^0-9]/g, '') || '15';
  return httpClient.getBlob(`/Invoice/${cleanId}/pdf`);
}

/**
 * GET http://whateq.runasp.net/api/Invoice/15/pdf
 * Explicit helper to fetch invoice 15 PDF directly as requested.
 */
export async function getInvoice15PdfBlob(): Promise<Blob> {
  return getInvoicePdfBlob(15);
}

/**
 * Returns the direct absolute API URL for the PDF (e.g. http://whateq.runasp.net/api/Invoice/15/pdf).
 */
export function getInvoicePdfDirectUrl(invoiceId: number | string = 15): string {
  const cleanId = String(invoiceId).replace(/[^0-9]/g, '') || '15';
  return `http://whateq.runasp.net/api/Invoice/${cleanId}/pdf`;
}

/**
 * Downloads the PDF blob locally via browser save dialog/link.
 */
export function triggerPdfDownload(blob: Blob, filename = 'watheq_invoice.pdf'): void {
  const url = window.URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  window.URL.revokeObjectURL(url);
}

/**
 * POST /api/Invoice/{id}/share/whatsapp
 * Triggers backend WhatsApp sharing notification for the invoice.
 */
export async function shareInvoiceViaWhatsApp(
  invoiceId: number | string,
  request: ShareInvoiceRequest
): Promise<ShareInvoiceResponseDto> {
  const cleanId = String(invoiceId).replace(/[^0-9]/g, '') || '15';
  return httpClient.post<ShareInvoiceResponseDto>(`/Invoice/${cleanId}/share/whatsapp`, request);
}

/**
 * Converts API errors into clean, user-facing Arabic messages.
 */
export function toInvoiceErrorMessage(error: unknown): string {
  if (error instanceof ApiError) {
    const body = error.body as {
      result?: { code?: number; message?: string };
      message?: string;
      errors?: Record<string, string[]>;
    } | null;

    if (body?.result?.message) {
      return body.result.message;
    }
    if (body?.message) {
      return body.message;
    }
    if (body?.errors) {
      const first = Object.values(body.errors).flat()[0];
      if (first) return first;
    }

    if (error.status === 404) {
      return 'الفاتورة المحددة غير موجودة في سجلات الخادم (The specified invoice does not exist).';
    }
    if (error.status === 400) {
      return 'بيانات الفاتورة غير صحيحة، يرجى مراجعة المدخلات.';
    }
    if (error.status === 401) {
      return 'انتهت جلستك، يرجى إعادة تسجيل الدخول.';
    }
    if (error.status === 500) {
      return 'حدث خطأ في خادم الفواتير، يرجى المحاولة لاحقاً.';
    }
  }
  return 'تعذر الاتصال بخادم الفواتير، يرجى التحقق من اتصال الإنترنت.';
}
